// Generated by tools/build_bible_db.py from the files in assets/db - do not edit.
/** Bible versions shipped inside the app: id -> asset module. */
export const BUNDLED: Record<string, number> = {
  AMH1954: require('@/assets/db/AMH1954.db'),
  KJV: require('@/assets/db/KJV.db'),
  BSB: require('@/assets/db/BSB.db'),
  WEB: require('@/assets/db/WEB.db'),
  ASV: require('@/assets/db/ASV.db'),
  YLT: require('@/assets/db/YLT.db'),
  WBT: require('@/assets/db/WBT.db'),
};
